namespace Chinese

open MyTypes

module Kangxi =
    
    let getRadicals() =
        seq {
            { Symbol = '一'; Number = 1 }
            { Symbol = '丨'; Number = 2 }
            { Symbol = '丶'; Number = 3 }
            { Symbol = '丿'; Number = 4 }
            { Symbol = '乙'; Number = 5 }
            { Symbol = '乛'; Number = 5 }
            { Symbol = '⺄'; Number = 5 }
            { Symbol = '乚'; Number = 5 }
            { Symbol = '乙'; Number = 5 }
            { Symbol = '乙'; Number = 5 }
            { Symbol = '乀'; Number = 5 }
            { Symbol = '亅'; Number = 6 }
            { Symbol = '二'; Number = 7 }
            { Symbol = '亠'; Number = 8 }
            { Symbol = '人'; Number = 9 }
            { Symbol = '亻'; Number = 9 }
            { Symbol = '儿'; Number = 10 }
            { Symbol = '兒'; Number = 10 }
            { Symbol = '入'; Number = 11 }
            { Symbol = '八'; Number = 12 }
            { Symbol = '丷'; Number = 12 }
            { Symbol = '冂'; Number = 13 }
            { Symbol = '冖'; Number = 14 }
            { Symbol = '冫'; Number = 15 }
            { Symbol = '几'; Number = 16 }
            { Symbol = '凵'; Number = 17 }
            { Symbol = '刀'; Number = 18 }
            { Symbol = '刂'; Number = 18 }
            { Symbol = '⺈'; Number = 18 }
            { Symbol = '力'; Number = 19 }
            { Symbol = '勹'; Number = 20 }
            { Symbol = '匕'; Number = 21 }
            { Symbol = '匚'; Number = 22 }
            { Symbol = '匸'; Number = 23 }
            { Symbol = '十'; Number = 24 }
            { Symbol = '卜'; Number = 25 }
            { Symbol = '卩'; Number = 26 }
            { Symbol = '㔾'; Number = 26 }
            { Symbol = '厂'; Number = 27 }
            { Symbol = '廠'; Number = 27 }
            { Symbol = '厶'; Number = 28 }
            { Symbol = '又'; Number = 29 }
            { Symbol = '口'; Number = 30 }
            { Symbol = '囗'; Number = 31 }
            { Symbol = '土'; Number = 32 }
            { Symbol = '士'; Number = 33 }
            { Symbol = '夂'; Number = 34 }
            { Symbol = '夊'; Number = 35 }
            { Symbol = '夕'; Number = 36 }
            { Symbol = '大'; Number = 37 }
            { Symbol = '女'; Number = 38 }
            { Symbol = '子'; Number = 39 }
            { Symbol = '宀'; Number = 40 }
            { Symbol = '寸'; Number = 41 }
            { Symbol = '小'; Number = 42 }
            { Symbol = '⺌'; Number = 42 }
            { Symbol = '⺍'; Number = 42 }
            { Symbol = '尢'; Number = 43 }
            { Symbol = '尣'; Number = 43 }
            { Symbol = '尸'; Number = 44 }
            { Symbol = '屍'; Number = 44 }
            { Symbol = '屮'; Number = 45 }
            { Symbol = '山'; Number = 46 }
            { Symbol = '巛'; Number = 47 }
            { Symbol = '川'; Number = 47 }
            { Symbol = '工'; Number = 48 }
            { Symbol = '己'; Number = 49 }
            { Symbol = '巾'; Number = 50 }
            { Symbol = '干'; Number = 51 }
            { Symbol = '乾'; Number = 51 }
            { Symbol = '幹'; Number = 51 }
            { Symbol = '幺'; Number = 52 }
            { Symbol = '么'; Number = 52 }
            { Symbol = '广'; Number = 53 }
            { Symbol = '廣'; Number = 53 }
            { Symbol = '廴'; Number = 54 }
            { Symbol = '廾'; Number = 55 }
            { Symbol = '弋'; Number = 56 }
            { Symbol = '弓'; Number = 57 }
            { Symbol = '彐'; Number = 58 }
            { Symbol = '彑'; Number = 58 }
            { Symbol = '彡'; Number = 59 }
            { Symbol = '彳'; Number = 60 }
            { Symbol = '心'; Number = 61 }
            { Symbol = '忄'; Number = 61 }
            { Symbol = '⺗'; Number = 61 }
            { Symbol = '戈'; Number = 62 }
            { Symbol = '戶'; Number = 63 }
            { Symbol = '户'; Number = 63 }
            { Symbol = '戸'; Number = 63 }
            { Symbol = '手'; Number = 64 }
            { Symbol = '扌'; Number = 64 }
            { Symbol = '龵'; Number = 64 }
            { Symbol = '支'; Number = 65 }
            { Symbol = '攴'; Number = 66 }
            { Symbol = '攵'; Number = 66 }
            { Symbol = '文'; Number = 67 }
            { Symbol = '斗'; Number = 68 }
            { Symbol = '斤'; Number = 69 }
            { Symbol = '方'; Number = 70 }
            { Symbol = '无'; Number = 71 }
            { Symbol = '旡'; Number = 71 }
            { Symbol = '日'; Number = 72 }
            { Symbol = '曰'; Number = 73 }
            { Symbol = '月'; Number = 74 }
            { Symbol = '木'; Number = 75 }
            { Symbol = '欠'; Number = 76 }
            { Symbol = '止'; Number = 77 }
            { Symbol = '歹'; Number = 78 }
            { Symbol = '歺'; Number = 78 }
            { Symbol = '殳'; Number = 79 }
            { Symbol = '毋'; Number = 80 }
            { Symbol = '母'; Number = 80 }
            { Symbol = '比'; Number = 81 }
            { Symbol = '毛'; Number = 82 }
            { Symbol = '氏'; Number = 83 }
            { Symbol = '气'; Number = 84 }
            { Symbol = '氣'; Number = 84 }
            { Symbol = '水'; Number = 85 }
            { Symbol = '氵'; Number = 85 }
            { Symbol = '氺'; Number = 85 }
            { Symbol = '火'; Number = 86 }
            { Symbol = '灬'; Number = 86 }
            { Symbol = '爪'; Number = 87 }
            { Symbol = '爫'; Number = 87 }
            { Symbol = '父'; Number = 88 }
            { Symbol = '爻'; Number = 89 }
            { Symbol = '爿'; Number = 90 }
            { Symbol = '丬'; Number = 90 }
            { Symbol = '片'; Number = 91 }
            { Symbol = '牙'; Number = 92 }
            { Symbol = '牛'; Number = 93 }
            { Symbol = '牜'; Number = 93 }
            { Symbol = '⺧'; Number = 93 }
            { Symbol = '犬'; Number = 94 }
            { Symbol = '犭'; Number = 94 }
            { Symbol = '玄'; Number = 95 }
            { Symbol = '玉'; Number = 96 }
            { Symbol = '王'; Number = 96 }
            { Symbol = '玊'; Number = 96 }
            { Symbol = '瓜'; Number = 97 }
            { Symbol = '瓦'; Number = 98 }
            { Symbol = '甘'; Number = 99 }
            { Symbol = '生'; Number = 100 }
            { Symbol = '用'; Number = 101 }
            { Symbol = '田'; Number = 102 }
            { Symbol = '疋'; Number = 103 }
            { Symbol = '⺪'; Number = 103 }
            { Symbol = '疒'; Number = 104 }
            { Symbol = '癶'; Number = 105 }
            { Symbol = '白'; Number = 106 }
            { Symbol = '皮'; Number = 107 }
            { Symbol = '皿'; Number = 108 }
            { Symbol = '目'; Number = 109 }
            { Symbol = '⺫'; Number = 109 }
            { Symbol = '矛'; Number = 110 }
            { Symbol = '矢'; Number = 111 }
            { Symbol = '石'; Number = 112 }
            { Symbol = '示'; Number = 113 }
            { Symbol = '礻'; Number = 113 }
            { Symbol = '禸'; Number = 114 }
            { Symbol = '禾'; Number = 115 }
            { Symbol = '穴'; Number = 116 }
            { Symbol = '立'; Number = 117 }
            { Symbol = '竹'; Number = 118 }
            { Symbol = '⺮'; Number = 118 }
            { Symbol = '米'; Number = 119 }
            { Symbol = '糸'; Number = 120 }
            { Symbol = '糹'; Number = 120 }
            { Symbol = '纟'; Number = 120 }
            { Symbol = '缶'; Number = 121 }
            { Symbol = '网'; Number = 122 }
            { Symbol = '⺲'; Number = 122 }
            { Symbol = '罓'; Number = 122 }
            { Symbol = '⺳'; Number = 122 }
            { Symbol = '羊'; Number = 123 }
            { Symbol = '⺶'; Number = 123 }
            { Symbol = '⺷'; Number = 123 }
            { Symbol = '羽'; Number = 124 }
            { Symbol = '老'; Number = 125 }
            { Symbol = '耂'; Number = 125 }
            { Symbol = '而'; Number = 126 }
            { Symbol = '耒'; Number = 127 }
            { Symbol = '耳'; Number = 128 }
            { Symbol = '聿'; Number = 129 }
            { Symbol = '⺺'; Number = 129 }
            { Symbol = '⺻'; Number = 129 }
            { Symbol = '肉'; Number = 130 }
            { Symbol = '⺼'; Number = 130 }
            { Symbol = '臣'; Number = 131 }
            { Symbol = '自'; Number = 132 }
            { Symbol = '至'; Number = 133 }
            { Symbol = '臼'; Number = 134 }
            { Symbol = '舌'; Number = 135 }
            { Symbol = '舛'; Number = 136 }
            { Symbol = '舟'; Number = 137 }
            { Symbol = '艮'; Number = 138 }
            { Symbol = '色'; Number = 139 }
            { Symbol = '艸'; Number = 140 }
            { Symbol = '⺿'; Number = 140 }
            { Symbol = '⺾'; Number = 140 }
            { Symbol = '虍'; Number = 141 }
            { Symbol = '虫'; Number = 142 }
            { Symbol = '蟲'; Number = 142 }
            { Symbol = '血'; Number = 143 }
            { Symbol = '行'; Number = 144 }
            { Symbol = '衣'; Number = 145 }
            { Symbol = '⻂'; Number = 145 }
            { Symbol = '襾'; Number = 146 }
            { Symbol = '西'; Number = 146 }
            { Symbol = '覀'; Number = 146 }
            { Symbol = '見'; Number = 147 }
            { Symbol = '见'; Number = 147 }
            { Symbol = '角'; Number = 148 }
            { Symbol = '⻇'; Number = 148 }
            { Symbol = '⻆'; Number = 148 }
            { Symbol = '言'; Number = 149 }
            { Symbol = '訁'; Number = 149 }
            { Symbol = '讠'; Number = 149 }
            { Symbol = '谷'; Number = 150 }
            { Symbol = '豆'; Number = 151 }
            { Symbol = '豕'; Number = 152 }
            { Symbol = '豸'; Number = 153 }
            { Symbol = '貝'; Number = 154 }
            { Symbol = '贝'; Number = 154 }
            { Symbol = '赤'; Number = 155 }
            { Symbol = '走'; Number = 156 }
            { Symbol = '足'; Number = 157 }
            { Symbol = '⻊'; Number = 157 }
            { Symbol = '身'; Number = 158 }
            { Symbol = '車'; Number = 159 }
            { Symbol = '车'; Number = 159 }
            { Symbol = '辛'; Number = 160 }
            { Symbol = '辰'; Number = 161 }
            { Symbol = '辵'; Number = 162 }
            { Symbol = '⻌'; Number = 162 }
            { Symbol = '⻍'; Number = 162 }
            { Symbol = '⻎'; Number = 162 }
            { Symbol = '邑'; Number = 163 }
            { Symbol = '⻏'; Number = 163 }
            { Symbol = '酉'; Number = 164 }
            { Symbol = '釆'; Number = 165 }
            { Symbol = '里'; Number = 166 }
            { Symbol = '金'; Number = 167 }
            { Symbol = '釒'; Number = 167 }
            { Symbol = '钅'; Number = 167 }
            { Symbol = '長'; Number = 168 }
            { Symbol = '镸'; Number = 168 }
            { Symbol = '长'; Number = 168 }
            { Symbol = '門'; Number = 169 }
            { Symbol = '门'; Number = 169 }
            { Symbol = '阜'; Number = 170 }
            { Symbol = '⻖'; Number = 170 }
            { Symbol = '隶'; Number = 171 }
            { Symbol = '隹'; Number = 172 }
            { Symbol = '雨'; Number = 173 }
            { Symbol = '青'; Number = 174 }
            { Symbol = '靑'; Number = 174 }
            { Symbol = '非'; Number = 175 }
            { Symbol = '面'; Number = 176 }
            { Symbol = '靣'; Number = 176 }
            { Symbol = '革'; Number = 177 }
            { Symbol = '韋'; Number = 178 }
            { Symbol = '韦'; Number = 178 }
            { Symbol = '韭'; Number = 179 }
            { Symbol = '音'; Number = 180 }
            { Symbol = '頁'; Number = 181 }
            { Symbol = '页'; Number = 181 }
            { Symbol = '風'; Number = 182 }
            { Symbol = '风'; Number = 182 }
            { Symbol = '飛'; Number = 183 }
            { Symbol = '飞'; Number = 183 }
            { Symbol = '食'; Number = 184 }
            { Symbol = '飠'; Number = 184 }
            { Symbol = '饣'; Number = 184 }
            { Symbol = '首'; Number = 185 }
            { Symbol = '香'; Number = 186 }
            { Symbol = '馬'; Number = 187 }
            { Symbol = '马'; Number = 187 }
            { Symbol = '骨'; Number = 188 }
            { Symbol = '⻣'; Number = 188 }
            { Symbol = '高'; Number = 189 }
            { Symbol = '髙'; Number = 189 }
            { Symbol = '髟'; Number = 190 }
            { Symbol = '鬥'; Number = 191 }
            { Symbol = '门'; Number = 191 }
            { Symbol = '鬯'; Number = 192 }
            { Symbol = '鬲'; Number = 193 }
            { Symbol = '鬼'; Number = 194 }
            { Symbol = '魚'; Number = 195 }
            { Symbol = '鱼'; Number = 195 }
            { Symbol = '鳥'; Number = 196 }
            { Symbol = '鸟'; Number = 196 }
            { Symbol = '鹵'; Number = 197 }
            { Symbol = '卤'; Number = 197 }
            { Symbol = '鹿'; Number = 198 }
            { Symbol = '麥'; Number = 199 }
            { Symbol = '麦'; Number = 199 }
            { Symbol = '麻'; Number = 200 }
            { Symbol = '黃'; Number = 201 }
            { Symbol = '黄'; Number = 201 }
            { Symbol = '黍'; Number = 202 }
            { Symbol = '黑'; Number = 203 }
            { Symbol = '黹'; Number = 204 }
            { Symbol = '黽'; Number = 205 }
            { Symbol = '黾'; Number = 205 }
            { Symbol = '鼎'; Number = 206 }
            { Symbol = '鼓'; Number = 207 }
            { Symbol = '鼠'; Number = 208 }
            { Symbol = '鼻'; Number = 209 }
            { Symbol = '齊'; Number = 210 }
            { Symbol = '斉'; Number = 210 }
            { Symbol = '齐'; Number = 210 }
            { Symbol = '齒'; Number = 211 }
            { Symbol = '齿'; Number = 211 }
            { Symbol = '龍'; Number = 212 }
            { Symbol = '龙'; Number = 212 }
            { Symbol = '龜'; Number = 213 }
            { Symbol = '龟'; Number = 213 }
            { Symbol = '龠'; Number = 214 } 
        }
